name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.SECURE_TOKEN }}

      - name: Set Image URLs
        run: |
          echo "FRONTEND_IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-frontend:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "BACKEND_IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-backend:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./source/DrawAndGuess/DrawAndGuess.Client/client
          file: ./source/DrawAndGuess/DrawAndGuess.Client/client/Dockerfile
          push: true
          tags: ${{ env.FRONTEND_IMAGE_URL }}

      # - name: Build and Push Backend Image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./source/DrawAndGuess/DrawAndGuess.API/DrawAndGuess.API
      #     file: ./source/DrawAndGuess/DrawAndGuess.API/DrawAndGuess.API/Dockerfile
      #     push: true
      #     tags: ${{ env.BACKEND_IMAGE_URL }}

      - name: Deploy Frontend to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.FRONTEND_APP_NAME }}"
          token: "${{ secrets.FRONTEND_APP_TOKEN }}"
          image: ${{ env.FRONTEND_IMAGE_URL }}

      # - name: Deploy Backend to CapRover
      #   uses: caprover/deploy-from-github@v1.1.2
      #   with:
      #     server: "${{ secrets.CAPROVER_SERVER }}"
      #     app: "${{ secrets.BACKEND_APP_NAME }}"
      #     token: "${{ secrets.BACKEND_APP_TOKEN }}"
      #     image: ${{ env.BACKEND_IMAGE_URL }}
