name: Build and Deploy Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.SECURE_TOKEN }}

      - name: Set Image URLs
        run: |
          echo "FRONTEND_IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-frontend:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "API_IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-backend:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "SIGNALR_IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-signalr:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./source/DrawAndGuess/DrawAndGuess.Client/client
          file: ./source/DrawAndGuess/DrawAndGuess.Client/client/Dockerfile
          push: true
          tags: ${{ env.FRONTEND_IMAGE_URL }}

      - name: Build and Push SignalR Image
        uses: docker/build-push-action@v5
        with:
          context: ./source/DrawAndGuess/
          file: ./source/DrawAndGuess/DrawAndGuess.SignalR/Dockerfile
          push: true
          tags: ${{ env.SIGNALR_IMAGE_URL }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./source/DrawAndGuess/
          file: ./source/DrawAndGuess/DrawAndGuess.API/Dockerfile
          push: true
          tags: ${{ env.API_IMAGE_URL }}

      - name: Deploy Frontend to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.FRONTEND_APP_NAME }}"
          token: "${{ secrets.FRONTEND_APP_TOKEN }}"
          image: ${{ env.FRONTEND_IMAGE_URL }}

      - name: Deploy SignalR Hubs to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.SIGNALR_APP_NAME }}"
          token: "${{ secrets.SIGNALR_APP_TOKEN }}"
          image: ${{ env.SIGNALR_IMAGE_URL }}

      - name: Deploy Backend to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.API_APP_NAME }}"
          token: "${{ secrets.API_APP_TOKEN }}"
          image: ${{ env.API_IMAGE_URL }}

      - name: Create GitHub Deployment
        id: create_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/deployments
          environment: production
          ref: ${{ github.ref }}
          description: "Deployment to production"
          auto_merge: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Deployment Status
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/deployments/:deployment_id/statuses
          deployment_id: ${{ steps.create_deployment.outputs.deployment_id }}
          state: success
          token: ${{ secrets.GITHUB_TOKEN }}
