name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Cache Node.js dependencies
      uses: actions/cache@v3
      with:
        path: source/DrawAndGuess/DrawAndGuess.Client/client/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('source/DrawAndGuess/DrawAndGuess.Client/client/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install dependencies and Playwright Browsers
      working-directory: source/DrawAndGuess/DrawAndGuess.Client/client
      run: |
        npm ci
        npx playwright install --with-deps

    - name: Run Playwright tests
      working-directory: source/DrawAndGuess/DrawAndGuess.Client/client
      run: npx playwright test

    - name: Upload Playwright report as artifact
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: source/DrawAndGuess/DrawAndGuess.Client/client/playwright-report/
        retention-days: 30

    - name: Upload HTML report to Azure
      shell: bash
      run: |
            REPORT_DIR="run-${{ github.run_id }}-${{ github.run_attempt }}"
            REPORT_PATH="source/DrawAndGuess/DrawAndGuess.Client/client/playwright-report"
            echo "Checking if the report directory exists: $REPORT_PATH"
            if [ -d "$REPORT_PATH" ]; then
              azcopy cp --recursive "$REPORT_PATH" "https://drawandguess.blob.core.windows.net/\$web/$REPORT_DIR"
              echo "::notice title=HTML report url::https://drawandguess.z1.web.core.windows.net/$REPORT_DIR/playwright-report/index.html"
            else
              echo "::error::Playwright report directory does not exist: $REPORT_PATH"
            fi
      env:
            AZCOPY_AUTO_LOGIN_TYPE: SPN
            AZCOPY_SPA_APPLICATION_ID: ${{ secrets.AZCOPY_SPA_APPLICATION_ID }}
            AZCOPY_SPA_CLIENT_SECRET: ${{ secrets.AZCOPY_SPA_CLIENT_SECRET }}
            AZCOPY_TENANT_ID: ${{ secrets.AZCOPY_TENANT_ID }}

    - name: Comment with PR status and HTML report URL
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          REPORT_DIR="run-${{ github.run_id }}-${{ github.run_attempt }}"
          const reportUrl = `https://drawandguess.z1.web.core.windows.net/${REPORT_DIR}/playwright-report/index.html`;
          const comments = [
            `The Playwright test report is available at: ${reportUrl}`
          ];
          for (const body of comments) {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });
          }
