name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies and Playwright Browsers
      working-directory: source/DrawAndGuess/DrawAndGuess.Client/client
      run: |
        npm install
        npm ci
        npx playwright install --with-deps

    - name: Run Playwright tests
      working-directory: source/DrawAndGuess/DrawAndGuess.Client/client
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: source/DrawAndGuess/DrawAndGuess.Client/client/playwright-report/
        retention-days: 30

    - name: Upload HTML report to Azure
      shell: bash
      run: |
          REPORT_DIR="run-${{ github.run_id }}-${{ github.run_attempt }}"
          REPORT_PATH="source/DrawAndGuess/DrawAndGuess.Client/client/playwright-report/*"
          echo "Checking if the report directory exists: $REPORT_PATH"
          if [ -d "$REPORT_PATH" ]; then
            azcopy cp --recursive "$REPORT_PATH" "https://<STORAGE_ACCOUNT_NAME>.blob.core.windows.net/\$web/$REPORT_DIR"
            echo "::notice title=HTML report url::https://<STORAGE_ACCOUNT_NAME>.z1.web.core.windows.net/\$web/$REPORT_DIR/index.html"
          else
            echo "::error::Playwright report directory does not exist: $REPORT_PATH"
          fi
        env:
          AZCOPY_AUTO_LOGIN_TYPE: SPN
          AZCOPY_SPA_APPLICATION_ID: ${{ secrets.AZCOPY_SPA_APPLICATION_ID }}
          AZCOPY_SPA_CLIENT_SECRET: ${{ secrets.AZCOPY_SPA_CLIENT_SECRET }}
          AZCOPY_TENANT_ID: ${{ secrets.AZCOPY_TENANT_ID }}
      
